---
- name: Download name
  set_fact:
    _cni_download: "cni-plugins-linux-{{ go_arch }}-v{{ cni_version }}"

- block:
    - name: Download cni-plugins to local folder
      get_url:
        url: "https://github.com/containernetworking/plugins/releases/download/v{{ cni_version }}/{{ _cni_download }}.tgz"
        dest: "/tmp/{{ _cni_download }}.tgz"
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      # delegate_to: localhost
      check_mode: false

    - name: Create target directory
      file:
        name: /opt/cni/bin
        state: directory

    - name: Unpack cni-plugins binaries
      unarchive:
        src: "/tmp/{{ _cni_download }}.tgz"
        dest: "/opt/cni/bin"
        creates: "/tmp/{{ _cni_download }}/bandwidth"
      # delegate_to: localhost
      check_mode: false
