---
- name: Install ignite(d)
  get_url:
    url: "https://github.com/weaveworks/ignite/releases/download/v{{ ignite_version }}/{{ item }}-{{ go_arch }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  check_mode: false
  with_items:
    - ignite
    - ignited
